# Generate .loadmods.cfg file
name: Generate loadmods file
# Run script automatically on push or when manually activated
on: [push, workflow_dispatch]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4
      
      - name: Generate a new loadmods file
        run: bash generate.sh

      - name: check for changes
        run: git status
      - name: Commit Changes
        run: |
          git config --local user.name "JavierMarcosFer"
          git add .
      - name: commit changed files
        run: git commit -m "Auto-updating .loadmods.cfg"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
